modLoader="javafml"
loaderVersion="[36,)"
license="BSD"
[[mods]]
modId="sanguinearsenal"
version="0.1.72"
displayName="Sanguine Arsenal"
logoFile="sanguine_arsenal.png"
credits="Sanguine Arsenal by the Decursio Team"
description='''
A small addon for the Eidolon mod
'''

[[dependencies.sanguinearsenal]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sanguinearsenal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sanguinearsenal]]
    modId = "eidolon"
    mandatory = true
    versionRange = "[0.2.7]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.sanguinearsenal]]
modId = "curios"
mandatory = true
versionRange = "[1.16.5-4.0.8.1,)"
ordering = "NONE"
side = "BOTH"

#optional

[[dependencies.sanguinearsenal]]
modId = "atum"
mandatory = false
versionRange = "[1.16.5-2.2.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sanguinearsenal]]
modId = "twilightforest"
mandatory = false
versionRange = "[1.16.5-4.0.546,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sanguinearsenal]]
modId = "classicbar"
mandatory = false
versionRange = "[4.1.0-1.16.5,)"
ordering = "AFTER"
side = "BOTH"

