modLoader="javafml"
loaderVersion="[36,)"
license="BSD"
[[mods]]
modId="sanguinearsenal"
version="0.2.0"
displayName="Sanguine Arsenal"
logoFile="sanguine_arsenal.png"
credits="Sanguine Arsenal by the Decursio Team"
description='''
A small addon for the Eidolon mod
'''

[[dependencies.sanguinearsenal]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sanguinearsenal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sanguinearsenal]]
    modId = "eidolon"
    mandatory = true
    versionRange = "[0.3.0,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.sanguinearsenal]]
modId = "curios"
mandatory = true
versionRange = "[1.19.2-5.1.1.0,)"
ordering = "NONE"
side = "BOTH"

#optional

#[[dependencies.sanguinearsenal]]
#modId = "classicbar"
#mandatory = false
#versionRange = "[6-1.19.2,)"
#ordering = "AFTER"
#side = "BOTH"

